services:
  - type: web
    name: devprofile-portfolio
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://devprofile-portfolio.onrender.com
      - key: ASSET_URL
        value: https://devprofile-portfolio.onrender.com
      - key: UNISENDER_API_KEY
        value: "6izu9kgb3mm9gt3e8483yqi74abnri337d539p4e"