services:
  - type: web
    name: devprofile-portfolio
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://devprofile-portfolio.onrender.com
      - key: ASSET_URL
        value: https://devprofile-portfolio.onrender.com
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.yandex.ru
      - key: MAIL_PORT
        value: "465"
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: MAIL_USERNAME
        value: filatowa.l2010@yandex.ru
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: filatowa.l2010@yandex.ru
      - key: MAIL_FROM_NAME
        value: "Елена Фионина"